from pathlib import Path
import pandas as pd

def load_data(data134Path="data/Data2022"):
    data_path = Path(data134Path)
    txt_files = list(data_path.glob("*.txt"))
    three_d_files = [f for f in data_path.glob("*.3d") 
                     if 'Zone.Identifier' not in str(f)]
    all_files = sorted(txt_files + three_d_files, key=lambda x: x.name.lower())

    dfs_list = []
    for fname in all_files:
        df = pd.read_csv(fname)
        df.columns = df.columns.str.strip()
        dfs_list.append(df)
    
    return dfs_list, all_files

def get_species():
    return {
    'ADGCONT3d.txt': 'A',
    'AKG3d.txt': 'A',
    'Ala33d.txt': 'A',  # Note: Table shows "Ala333.txt"
    'AlaMR3d.txt': 'A',
    'Alanine3d.txt': 'A',
    'Albertit3d.txt': 'B',
    'Allende23d.txt': 'A',
    'Allende3d.txt': 'A',
    'AMAX.3d.txt': 'B',
    'ASPHLTMM3d.txt': 'B',
    'ASPMR3d.txt': 'A',
    'BARLEY.3d' : 'B',
    'BAKE.3d' : None,  # Not in Table S1
    'BASMATI.3d' : 'B',
    'BBRSOIL1.3d' : 'B',
    'Bcereus3d.txt': 'B',
    'BIOFIL.3d' : 'B',
    'Blank33d.txt': None,  # Not in Table S1
    'Blank43d.txt': None,  # Not in Table S1
    'Blank53d.txt': None,  # Not in Table S1
    'Blank63d.txt': None,  # Not in Table S1
    'Bonnetf3d.txt': 'B',
    'brnrice3d.txt': 'B',
    'Bsubtil3d.txt': 'B',
    'Bulgur3d.txt': 'B',
    'Cannak3d.txt': 'A',
    'Cannelco3d.txt': 'B',
    'Carnos3d.txt': 'B',
    'Cedarto3d.txt': 'B',
    'Chiles3d.txt': 'B',
    'Chiltin3d.txt': 'B',
    'Citron3d.txt': 'B',
    'CIWSoil13d.txt': 'B',
    'Collagen3d.txt': 'B',
    'CRDPAR3d.txt': 'B',
    'Cyanob23d.txt': 'B',
    'Cyanob3d.txt': 'B',
    'CysMR23d.txt': 'A',
    'CysMR3d.txt': 'A',
    'Devons3d.txt': 'B',
    'DGlucose3d.txt': 'A',
    'DNA3d.txt': 'A',
    'ECO33DB.txt': 'B',
    'Ecoli13d.txt': 'B',
    'ED513933d.txt': 'A',
    'Elaterit3d.txt': 'B',
    'Entaer3d.txt': 'B',
    'Ferron3d.txt': 'B',
    'GCN3d.txt': 'A',
    'Gelatin3d.txt': 'B',
    'GlnMR3d.txt': 'A',
    'GluMR23d.txt': 'A',
    'GluMR3d.txt': 'A',
    'Glycine3d.txt': 'A',
    'GlyMR3d.txt': 'A',
    'Glyoxaci3d.txt': 'A',
    'Grass3d.txt': 'B',
    'Grnrivs3d.txt': 'B',
    'Hair3d.txt': 'B',
    'HCN531723d.txt': 'A',
    'HMT3d.txt': 'A',
    'Humica3d.txt': 'B',
    'Jetwhtby3d.txt': 'B',
    'Kraton23d.txt': 'A',
    'Kraton3d.txt': 'A', # reminder to figure out the diff between this and above
    'LAsp3d.txt': 'A',
    'Lcys3d.txt': 'A',
    'Lescel3d.txt': 'B',
    'Leuglulq3d.txt': 'A',
    'Leuglumr3d.txt': 'A',
    'Lgln3d.txt': 'A',
    'Lglu3d.txt': 'A',
    'Lhis3d.txt': 'A',
    'Lichen3d.txt': 'B',
    'Lleu3d.txt': 'A',
    'Llys3d.txt': 'A',
    'Lmet3d.txt': 'A',
    'Lphe3d.txt': 'A',
    'Lpro3d.txt': 'A',
    'Lser3d.txt': 'A',
    'Ltyr3d.txt': 'A',
    'Lysmr3d.txt': 'A',
    'Malic3d.txt': 'A',
    'MetMRLQ3d.txt': 'A',
    'Metseqah3d.txt': 'B',
    'Miclut3d.txt': 'B',
    'Moss3d.txt': 'B',
    'Mythic3d.txt': 'B',
    'Nrk1_RT3d.txt': 'A',
    'Nrk2_853d.txt': 'A',
    'Nrk2rt3d.txt': 'A',
    'Nrka1853d.txt': 'A',
    'Nylon3d.txt': 'A',
    'OakLeaf3d.txt': 'B',
    'Oat3d.txt': 'B',
    'Okra3d.txt': 'B',
    'p1165lp3d.txt': 'A',
    'p1165ls3d.txt': 'A',
    'p118l2s3d.txt': 'A',
    'p82_30B3d.txt': 'B',
    'p82_313d.txt': 'B',
    'p82_31B3d.txt': 'B',
    'p82_323d.txt': 'B',
    'p82_403d.txt': 'A',
    'p82_473d.txt': 'A',
    'p82_513d.txt': 'A',
    'p82_523d.txt': 'A',
    'p825085C3d.txt': 'A',
    'p8253fr3d.txt': 'A',
    'pacampa23d.txt': 'A',
    'pacampac3d.txt': 'A',
    'peat3d.txt': 'B',
    'pemagma3d.txt': 'A',
    'phemr3d.txt': 'A',
    'Pitt8Coa3d.txt': 'B',
    'PP_Test3d.txt': None,  # Not in Table S1
    'PPTest23d.txt': None,  # Not in Table S1
    'ProMR3d.txt': 'A',
    'Pumpkin3d.txt': 'B',
    'Quisqui3d.txt': 'B',
    'Rdlent3d.txt': 'B',
    'RNA3d.txt': 'A',
    'Scerev3d.txt': 'B',
    'SerMar3d.txt': 'B',
    'SerMRSO3d.txt': 'A',
    'Shungite3d.txt': 'B',
    'SIOM25023d.txt': 'A',
    'SIOM250D3d.txt': 'A',
    'Sodpyr3d.txt': 'A',
    'Staepi3d.txt': 'B',
    'Strob3d.txt': 'A',
    'TAGL5b3d.txt': 'A',
    'TAGLIII3d.txt': 'A',
    'TAGLIIV3d.txt': 'A',
    'TAGLKIIH3d.txt': 'A',
    'TAGLold3d.txt': 'A',
    'TglkIIH23d.txt': 'A',
    'TglkIIV23d.txt': 'A',
    'Torbanit3d.txt': 'B',
    'Tyrglumr3d.txt': 'A',
    'Westflds3d.txt': 'B'
}

def get_age():
    return {
    'ADGCONT3d.txt': 0,
    'AKG3d.txt': 0,
    'Ala33d.txt': 0,  # Assuming same as other amino acids
    'AlaMR3d.txt': 0,
    'Alanine3d.txt': 0,
    'Albertit3d.txt': 389,  # Midpoint of 359-419
    'Allende23d.txt': 4500,
    'Allende3d.txt': 4500,
    'AMAX.3d.txt': None,  # ND in table
    'ASPHLTMM3d.txt': None,  # ND
    'ASPMR3d.txt': 0,
    'BARLEY.3d' : 0,
    'BASMATI.3d' : 0,
    'BBRSOIL1.3d' : 0,
    'Bcereus3d.txt': 0,
    'Blank33d.txt': None,  # Not in table
    'Blank43d.txt': None,  # Not in table
    'Blank53d.txt': None,  # Not in table
    'Blank63d.txt': None,  # Not in table
    'BIOFIL.3d': 0,
    'Bonnetf3d.txt': 0,
    'brnrice3d.txt': 0,
    'Bsubtil3d.txt': 0,
    'Bulgur3d.txt': 0,
    'Cannak3d.txt': 4500,
    'Cannelco3d.txt': None,  # ND
    'Carnos3d.txt': None,  # ND
    'Cedarto3d.txt': 0,
    'Chiles3d.txt': 0,
    'Chiltin3d.txt': 0,
    'Citron3d.txt': 0,
    'CIWSoil13d.txt': 0,
    'Collagen3d.txt': 0,
    'CRDPAR3d.txt': 0,
    'Cyanob23d.txt': 0,
    'Cyanob3d.txt': 0,
    'CysMR23d.txt': 0,
    'CysMR3d.txt': 0,
    'Devons3d.txt': 239.5,  # Midpoint of 60-419
    'DGlucose3d.txt': 0,
    'DNA3d.txt': 0,
    'ECO33DB.txt': 0,
    'Ecoli13d.txt': 0,
    'ED513933d.txt': 0,
    'Elaterit3d.txt': None,  # ND
    'Entaer3d.txt': 0,
    'Ferron3d.txt': 83.25,  # Midpoint of 100.5-66
    'GCN3d.txt': 0,
    'Gelatin3d.txt': 0,
    'GlnMR3d.txt': 0,
    'GluMR23d.txt': 0,
    'GluMR3d.txt': 0,
    'Glycine3d.txt': 0,
    'GlyMR3d.txt': 0,
    'Glyoxaci3d.txt': 0,
    'Grass3d.txt': 0,
    'Grnrivs3d.txt': 45,  # Midpoint of 34-56
    'Hair3d.txt': 0,
    'HCN531723d.txt': 0,
    'HMT3d.txt': 0,
    'Humica3d.txt': 0,
    'Jetwhtby3d.txt': 180,
    'Kraton23d.txt': 0,
    'Kraton3d.txt': 0,
    'LAsp3d.txt': 0,
    'Lcys3d.txt': 0,
    'Lescel3d.txt': 0,
    'Leuglulq3d.txt': 0,
    'Leuglumr3d.txt': 0,
    'Lgln3d.txt': 0,
    'Lglu3d.txt': 0,
    'Lhis3d.txt': 0,
    'Lichen3d.txt': 0,
    'Lleu3d.txt': 0,
    'Llys3d.txt': 0,
    'Lmet3d.txt': 0,
    'Lphe3d.txt': 0,
    'Lpro3d.txt': 0,
    'Lser3d.txt': 0,
    'Ltyr3d.txt': 0,
    'Lysmr3d.txt': 0,
    'Malic3d.txt': 0,
    'MetMRLQ3d.txt': 0,
    'Metseqah3d.txt': 45,
    'Miclut3d.txt': 0,
    'Moss3d.txt': 0,
    'Mythic3d.txt': 0,
    'Nrk1_RT3d.txt': 0,
    'Nrk2_853d.txt': 0,
    'Nrk2rt3d.txt': 0,
    'Nrka1853d.txt': 0,
    'Nylon3d.txt': 0,
    'OakLeaf3d.txt': 0,
    'Oat3d.txt': 0,
    'Okra3d.txt': 0,
    'p1165lp3d.txt': 0,
    'p1165ls3d.txt': 0,
    'p118l2s3d.txt': 0,
    'p82_30B3d.txt': None,  # ND
    'p82_313d.txt': 122.5,  # Midpoint of 100-145
    'p82_31B3d.txt': 122.5,  # Midpoint of 100-145
    'p82_323d.txt': None,  # ND
    'p82_403d.txt': 0,
    'p82_473d.txt': 0,
    'p82_513d.txt': 0,
    'p82_523d.txt': 0,
    'p825085C3d.txt': 0,
    'p8253fr3d.txt': 0,
    'pacampa23d.txt': 0,
    'pacampac3d.txt': 0,
    'peat3d.txt': 0.012,
    'pemagma3d.txt': 0,
    'phemr3d.txt': 0,
    'Pitt8Coa3d.txt': 297.5,  # Midpoint of 265-330
    'ProMR3d.txt': 0,
    'Pumpkin3d.txt': 0,
    'PP_Test3d.txt': None,  # Not in table
    'PPTest23d.txt': None,  # Not in table
    'Quisqui3d.txt': None,  # ND
    'Rdlent3d.txt': 0,
    'RNA3d.txt': 0,
    'Scerev3d.txt': 0,
    'SerMar3d.txt': 0,
    'SerMRSO3d.txt': 0,
    'Shungite3d.txt': 2000,
    'SIOM25023d.txt': 0,
    'SIOM250D3d.txt': 0,
    'Sodpyr3d.txt': 0,
    'Staepi3d.txt': 0,
    'Strob3d.txt': 0,
    'TAGL5b3d.txt': 4500,
    'TAGLIII3d.txt': 4500,
    'TAGLIIV3d.txt': 4500,
    'TAGLKIIH3d.txt': 4500,
    'TAGLold3d.txt': 4500,
    'TglkIIH23d.txt': 4500,
    'TglkIIV23d.txt': 4500,
    'Torbanit3d.txt': 275.5,  # Midpoint of 252-299
    'Tyrglumr3d.txt': 0,
    'Westflds3d.txt': 330  # Midpoint of 300-360
}
